name: FIESC & IEL Job Bot

on:
  schedule:
    - cron: '0 18 * * *'

  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python src/bot.py

      - name: Save job history (Commit)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Adiciona apenas os arquivos JSON da pasta src
          git add src/*.json
          
          # Checa se houve alguma mudança nos arquivos. Se sim, faz o commit e envia (push)
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update job history [skip ci]"
          git push